arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  constraints:
      goal_time: 0.8
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 0.2, goal: 0.4}
      joint2: {trajectory: 0.2, goal: 0.4}
      joint3: {trajectory: 0.2, goal: 0.4}
      joint4: {trajectory: 0.2, goal: 0.4}
      joint5: {trajectory: 0.2, goal: 0.4}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
